["org.gnome.desktop.background"]
picture-uri = "file://${MEDIA_DIR}/f40-01-night.png"
picture-uri-dark = "file://${MEDIA_DIR}/f40-01-night.png"

["org.gnome.desktop.screensaver"]
picture-uri = "file://${MEDIA_DIR}/f40-01-night.png"

["org.gnome.desktop.interface"]
color-scheme = "prefer-dark"
clock-show-weekday = true
clock-show-seconds = false
enable-hot-corners = true
show-battery-percentage = true
#monospace-font-name: "Jetbrains Mono 11"

["org.gnome.nautilus.preferences"]
show-hidden-files = true
default-folder-viewer = "list-view"
sort-directories-first = true

["org.gtk.Settings.FileChooser"]
show-hidden = true

["org.gtk.gtk4.Settings.FileChooser"]
show-hidden = true

["org.gnome.mutter"]
center-new-windows = true
attach-modal-dialogs = false

["org.gnome.desktop.peripherals.mouse"]
accel-profile = "flat"
speed = -0.2

["org.gnome.desktop.peripherals.keyboard"]
repeat = true
delay = 250
repeat-interval = 15

["org.gnome.desktop.peripherals.touchpad"]
tap-to-click = true
natural-scroll = true

["org.gnome.desktop.wm.preferences"]
button-layout = "right:minimize,close"

["org.gnome.desktop.input-sources"]
# xkb-options = ["caps:escape"]